Issue #35: Temporarily disabled mysql (as incoimpatible).
There was an error on migration:

NotSupportedError: MariaDB 10.5 or later is required (found 10.4.25).